/*
 * generated by Xtext 2.30.0
 */
package org.netapp.pcs.grammarVolumes.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class VolumesUiModule extends AbstractVolumesUiModule {

	public VolumesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
