/*
 * generated by Xtext 2.36.0
 */
package sesame.conditionBasedActivation.startingEndingExpression.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sesame.conditionBasedActivation.startingEndingExpression.parser.antlr.internal.InternalConditionsDslParser;
import sesame.conditionBasedActivation.startingEndingExpression.services.ConditionsDslGrammarAccess;

public class ConditionsDslParser extends AbstractAntlrParser {

	@Inject
	private ConditionsDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalConditionsDslParser createParser(XtextTokenStream stream) {
		return new InternalConditionsDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MainRules";
	}

	public ConditionsDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConditionsDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
