/*
 * generated by Xtext 2.36.0
 */
package sesame.conditionBasedActivation.startingEndingExpression.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ConditionsDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("sesame/conditionBasedActivation/startingEndingExpression/parser/antlr/internal/InternalConditionsDsl.tokens");
	}
}
