/*
 * generated by Xtext 2.36.0
 */
package workload.xtext_grammar.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import workload.xtext_grammar.parser.antlr.internal.InternalEffortsParser;
import workload.xtext_grammar.services.EffortsGrammarAccess;

public class EffortsParser extends AbstractAntlrParser {

	@Inject
	private EffortsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEffortsParser createParser(XtextTokenStream stream) {
		return new InternalEffortsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Main";
	}

	public EffortsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EffortsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
