/*
 * generated by Xtext 2.30.0
 */
package org.netapp.pcs.grammarSnapMirror;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ReplicationMappingsStandaloneSetup extends ReplicationMappingsStandaloneSetupGenerated {

	public static void doSetup() {
		new ReplicationMappingsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
