/*
 * generated by Xtext 2.30.0
 */
package org.netapp.pcs.grammarSnapMirror.ide;


/**
 * Use this class to register ide components.
 */
public class ReplicationMappingsIdeModule extends AbstractReplicationMappingsIdeModule {
}
