<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="flow" nsURI="http://www.obeo.fr/dsl/designer/sample/flow" nsPrefix="flow">
  <eClassifiers xsi:type="ecore:EClass" name="Fan" eSuperTypes="#//FlowElement #//Powered">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Physical"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeProcessor" eSuperTypes="#//System #//FlowTarget #//CapacityBound #//FlowSource">
    <eAnnotations source="syntax">
      <details key="feature" value="routingRules"/>
      <details key="derive" value="routingRulesList"/>
      <details key="grammar" value="fr.obeo.dsl.designer.sample.flow.xtext.FlowDesigner"/>
      <details key="entryRule" value="Main"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow" eSuperTypes="#//CapacityBound">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//FlowTarget" eOpposite="#//FlowTarget/incomingFlows"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//FlowSource" eOpposite="#//FlowSource/outgoingFlows"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapacityBound" abstract="true" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="load" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="#//Powered #//FlowSource #//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//FlowElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="temperature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powerOutputs" upperBound="-1"
        eType="#//PowerOutput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="powerInputs" upperBound="-1"
        eType="#//PowerInput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routingRules" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routingRulesList" upperBound="-1"
        eType="#//RoutingRule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutingRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//System"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="#//SystemProperty"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//PropertyUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparisonOperator" eType="#//ComparisonOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemStatus" eType="#//SystemStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SystemStatus">
    <eLiterals name="LOW"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="HIGH" value="2"/>
    <eLiterals name="NON_CRITICAL" value="3"/>
    <eLiterals name="CRITICAL" value="4"/>
    <eLiterals name="BLOCKER" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonOperator">
    <eLiterals name="Lower_than"/>
    <eLiterals name="Greather_than" value="1"/>
    <eLiterals name="Equals" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SystemProperty">
    <eLiterals name="Temperature"/>
    <eLiterals name="Weight" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PropertyUnit">
    <eLiterals name="Celsius"/>
    <eLiterals name="Fahrenheit" value="1"/>
    <eLiterals name="Kilograms" value="2"/>
    <eLiterals name="Pounds" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PowerOutput">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="power" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1000"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//PowerLink" containment="true" eOpposite="#//PowerLink/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Powered" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="powerStatus" lowerBound="1"
        eType="#//PoweredStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PoweredStatus">
    <eLiterals name="none"/>
    <eLiterals name="low" value="1"/>
    <eLiterals name="ok" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PowerInput"/>
  <eClassifiers xsi:type="ecore:EClass" name="PowerLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//PowerInput"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//PowerOutput"
        eOpposite="#//PowerOutput/links"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowSource" abstract="true" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingFlows" upperBound="-1"
        eType="#//DataFlow" containment="true" eOpposite="#//DataFlow/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Processor" eSuperTypes="#//FlowTarget #//CapacityBound #//FlowSource #//Powered #//Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowTarget" abstract="true" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingFlows" upperBound="-1"
        eType="#//DataFlow" eOpposite="#//DataFlow/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" eSuperTypes="#//FlowSource #//Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" lowerBound="1"
        eType="#//FlowElementStatus" defaultValueLiteral="active"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usage" lowerBound="1" eType="#//FlowElementUsage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FlowElementStatus">
    <eLiterals name="inactive"/>
    <eLiterals name="active" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FlowElementUsage">
    <eLiterals name="unused"/>
    <eLiterals name="low" value="1"/>
    <eLiterals name="standard" value="2"/>
    <eLiterals name="high" value="3"/>
    <eLiterals name="over" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
