/*
 * generated by Xtext 2.36.0
 */
package fr.obeo.dsl.designer.sample.flow.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.obeo.dsl.designer.sample.flow.xtext.FlowDesignerRuntimeModule;
import fr.obeo.dsl.designer.sample.flow.xtext.FlowDesignerStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FlowDesignerIdeSetup extends FlowDesignerStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FlowDesignerRuntimeModule(), new FlowDesignerIdeModule()));
	}
	
}
