/*
 * generated by Xtext 2.34.0
 */
package workload.xtext_grammar.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import workload.xtext_grammar.EffortsRuntimeModule;
import workload.xtext_grammar.EffortsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EffortsIdeSetup extends EffortsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EffortsRuntimeModule(), new EffortsIdeModule()));
	}
	
}
