/*
 * generated by Xtext 2.36.0
 */
package org.netapp.pcs.grammarVolumes.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVolumesScopeProvider extends DelegatingScopeProvider {
}
