/*
 * generated by Xtext 2.34.0
 */
package workload.xtext_grammar.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class EffortsProposalProvider extends AbstractEffortsProposalProvider {
}
