/*
 * generated by Xtext 2.34.0
 */
package workload.xtext_grammar;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EffortsStandaloneSetup extends EffortsStandaloneSetupGenerated {

	public static void doSetup() {
		new EffortsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
