/*
 * generated by Xtext 2.36.0
 */
package fr.obeo.dsl.designer.sample.flow.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.obeo.dsl.designer.sample.flow.xtext.ide.contentassist.antlr.internal.InternalFlowDesignerParser;
import fr.obeo.dsl.designer.sample.flow.xtext.services.FlowDesignerGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class FlowDesignerParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(FlowDesignerGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, FlowDesignerGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getSystemPropertyAccess().getAlternatives(), "rule__SystemProperty__Alternatives");
			builder.put(grammarAccess.getComparisonOperatorAccess().getAlternatives(), "rule__ComparisonOperator__Alternatives");
			builder.put(grammarAccess.getPropertyUnitAccess().getAlternatives(), "rule__PropertyUnit__Alternatives");
			builder.put(grammarAccess.getSystemStatusAccess().getAlternatives(), "rule__SystemStatus__Alternatives");
			builder.put(grammarAccess.getMainAccess().getGroup(), "rule__Main__Group__0");
			builder.put(grammarAccess.getMainAccess().getGroup_2(), "rule__Main__Group_2__0");
			builder.put(grammarAccess.getRoutingRuleAccess().getGroup(), "rule__RoutingRule__Group__0");
			builder.put(grammarAccess.getMainAccess().getRoutingRulesListAssignment_1(), "rule__Main__RoutingRulesListAssignment_1");
			builder.put(grammarAccess.getMainAccess().getRoutingRulesListAssignment_2_1(), "rule__Main__RoutingRulesListAssignment_2_1");
			builder.put(grammarAccess.getRoutingRuleAccess().getTargetAssignment_1(), "rule__RoutingRule__TargetAssignment_1");
			builder.put(grammarAccess.getRoutingRuleAccess().getPropertyNameAssignment_3(), "rule__RoutingRule__PropertyNameAssignment_3");
			builder.put(grammarAccess.getRoutingRuleAccess().getComparisonOperatorAssignment_4(), "rule__RoutingRule__ComparisonOperatorAssignment_4");
			builder.put(grammarAccess.getRoutingRuleAccess().getValueAssignment_5(), "rule__RoutingRule__ValueAssignment_5");
			builder.put(grammarAccess.getRoutingRuleAccess().getUnitAssignment_6(), "rule__RoutingRule__UnitAssignment_6");
			builder.put(grammarAccess.getRoutingRuleAccess().getSystemStatusAssignment_8(), "rule__RoutingRule__SystemStatusAssignment_8");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private FlowDesignerGrammarAccess grammarAccess;

	@Override
	protected InternalFlowDesignerParser createParser() {
		InternalFlowDesignerParser result = new InternalFlowDesignerParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public FlowDesignerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FlowDesignerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
