/*
 * generated by Xtext 2.30.0
 */
package org.netapp.pcs.grammarVolumes.ide;


/**
 * Use this class to register ide components.
 */
public class VolumesIdeModule extends AbstractVolumesIdeModule {
}
