/*
 * generated by Xtext 2.30.0
 */
package org.netapp.pcs.grammarSnapMirror.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;

import pcs.SnapMirror;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ReplicationMappingsScopeProvider extends AbstractReplicationMappingsScopeProvider {

	@Override
	public IScope getScope(EObject context, EReference reference) {
		if (reference.getName().equals("source_volume")) {
			 return Scopes.scopeFor(((SnapMirror)context).getSource_cvo().getVolumes());
		}
		else if (reference.getName().equals("destination_volume")) {
			 return Scopes.scopeFor(((SnapMirror)context).getDestination_cvo().getVolumes());
		}
		else {
			return super.getScope(context, reference);
		}
	}
	
}
