/*
 * generated by Xtext 2.36.0
 */
package structurizr.expressions.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStructurizrExpressionsScopeProvider extends DelegatingScopeProvider {
}
