/*
 * generated by Xtext 2.36.0
 */
package structurizr.expressions.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import structurizr.expressions.StructurizrExpressionsRuntimeModule;
import structurizr.expressions.StructurizrExpressionsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class StructurizrExpressionsIdeSetup extends StructurizrExpressionsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new StructurizrExpressionsRuntimeModule(), new StructurizrExpressionsIdeModule()));
	}
	
}
