/*
 * generated by Xtext 2.36.0
 */
package fr.obeo.dsl.designer.sample.flow.xtext.parser.antlr;

import com.google.inject.Inject;
import fr.obeo.dsl.designer.sample.flow.xtext.parser.antlr.internal.InternalFlowDesignerParser;
import fr.obeo.dsl.designer.sample.flow.xtext.services.FlowDesignerGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FlowDesignerParser extends AbstractAntlrParser {

	@Inject
	private FlowDesignerGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFlowDesignerParser createParser(XtextTokenStream stream) {
		return new InternalFlowDesignerParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Main";
	}

	public FlowDesignerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FlowDesignerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
