/*
 * generated by Xtext 2.36.0
 */
package fr.obeo.dsl.designer.sample.flow.xtext.ui;

import com.google.inject.Injector;
import fr.obeo.dsl.designer.sample.flow.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FlowDesignerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(XtextActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		XtextActivator activator = XtextActivator.getInstance();
		return activator != null ? activator.getInjector(XtextActivator.FR_OBEO_DSL_DESIGNER_SAMPLE_FLOW_XTEXT_FLOWDESIGNER) : null;
	}

}
