/*
 * generated by Xtext 2.36.0
 */
package structurizr.expressions.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StructurizrExpressionsAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("structurizr/expressions/parser/antlr/internal/InternalStructurizrExpressions.tokens");
	}
}
