/*
 * generated by Xtext 2.36.0
 */
package structurizr.expressions.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import structurizr.expressions.parser.antlr.internal.InternalStructurizrExpressionsParser;
import structurizr.expressions.services.StructurizrExpressionsGrammarAccess;

public class StructurizrExpressionsParser extends AbstractAntlrParser {

	@Inject
	private StructurizrExpressionsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStructurizrExpressionsParser createParser(XtextTokenStream stream) {
		return new InternalStructurizrExpressionsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EntryRule";
	}

	public StructurizrExpressionsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StructurizrExpressionsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
