/*
 * generated by Xtext 2.30.0
 */
package org.netapp.pcs.grammarVolumes.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class VolumesScopeProvider extends AbstractVolumesScopeProvider {

}
