/*
 * generated by Xtext 2.30.0
 */
package sesame.conditionBasedTimeLimited.startingExpression.ide;


/**
 * Use this class to register ide components.
 */
public class ConditionsDslIdeModule extends AbstractConditionsDslIdeModule {
}
