/*
 * generated by Xtext 2.30.0
 */
package sesame.conditionBasedTimeLimited.startingExpression.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import sesame.conditionBasedTimeLimited.startingExpression.ConditionsDslRuntimeModule;
import sesame.conditionBasedTimeLimited.startingExpression.ConditionsDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ConditionsDslIdeSetup extends ConditionsDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ConditionsDslRuntimeModule(), new ConditionsDslIdeModule()));
	}
	
}
