/*
 * generated by Xtext 2.30.0
 */
package org.netapp.pcs.grammarSnapMirror.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ReplicationMappingsUiModule extends AbstractReplicationMappingsUiModule {

	public ReplicationMappingsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
