/*
 * generated by Xtext 2.36.0
 */
package org.netapp.pcs.grammarSnapMirror.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReplicationMappingsScopeProvider extends DelegatingScopeProvider {
}
