/*
 * generated by Xtext 2.30.0
 */
package sesame.conditionBasedTimeLimited.startingExpression.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ConditionsDslProposalProvider extends AbstractConditionsDslProposalProvider {
}
