/*
 * generated by Xtext 2.36.0
 */
package sesame.conditionBasedActivation.startingEndingExpression.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import sesame.conditionBasedActivation.startingEndingExpression.ui.internal.StartingEndingExpressionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConditionsDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(StartingEndingExpressionActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		StartingEndingExpressionActivator activator = StartingEndingExpressionActivator.getInstance();
		return activator != null ? activator.getInjector(StartingEndingExpressionActivator.SESAME_CONDITIONBASEDACTIVATION_STARTINGENDINGEXPRESSION_CONDITIONSDSL) : null;
	}

}
