/*
 * generated by Xtext 2.36.0
 */
package fr.obeo.dsl.designer.sample.flow.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FlowDesignerUiModule extends AbstractFlowDesignerUiModule {

	public FlowDesignerUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
